/**
 * Generate the two files the subgraph cannot keep by hand: its ABI and its manifest.
 *
 * Both are derived, and both derive from things this repo already states once. The ABI comes
 * out of the compiled artifact, so an event whose signature changed cannot leave a stale copy
 * behind in `subgraph/abis/`. The manifest's address comes out of the deployment record, which
 * is already the repo's single answer to "where is the contract" - a second copy of an address
 * is a second thing that can be wrong, and wrong here means a subgraph that indexes nothing
 * and says nothing about why.
 *
 * The start block is the one fact neither file has. It is read from the mirror node the first
 * time it is needed and written back into the deployment record, so this runs offline
 * afterwards - which is what lets CI check the generated files for drift without a network.
 *
 * Run: npm run build && npm run subgraph:config
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { caip2, networkConfig } from "../src/config.js";
import { CONTRACT_NAME, readArtifact, readDeployment, writeDeployment } from "../src/pool/deployment.js";

const ROOT = fileURLToPath(new URL("../", import.meta.url));
const SUBGRAPH = join(ROOT, "subgraph");
const TEMPLATE = join(SUBGRAPH, "subgraph.template.yaml");
const MANIFEST = join(SUBGRAPH, "subgraph.yaml");
const ABI = join(SUBGRAPH, "abis", `${CONTRACT_NAME}.json`);

const ok = (m: string) => console.log(`  ok    ${m}`);
const info = (m: string) => console.log(`        ${m}`);

/**
 * `0.0.10404217@1788803605.204518884` -> `0.0.10404217-1788803605-204518884`.
 *
 * The SDK prints a transaction id with `@` and `.`; the mirror node's REST path wants dashes.
 * Same id, two spellings, and the REST call 404s on the wrong one rather than saying so.
 */
function mirrorTxId(transactionId: string): string {
  return transactionId.replace("@", "-").replace(/\.(\d+)$/, "-$1");
}

interface ContractResult {
  block_number?: number | null;
}

/**
 * The block the contract creation landed in.
 *
 * Note this is the *contract result* endpoint, not the transaction one: on Hedera a
 * transaction and its EVM result are separate records, and only the result carries a block
 * number, because only the EVM half has blocks.
 */
async function fetchCreationBlock(mirrorUrl: string, transactionId: string): Promise<number> {
  const path = `${mirrorUrl}/api/v1/contracts/results/${mirrorTxId(transactionId)}`;
  const res = await fetch(path);
  if (!res.ok) throw new Error(`mirror node returned ${res.status} for ${path}`);
  const body = (await res.json()) as ContractResult;
  if (typeof body.block_number !== "number") {
    throw new Error(`mirror node gave no block number for ${transactionId}`);
  }
  return body.block_number;
}

async function main(): Promise<void> {
  const cfg = networkConfig();
  const network = caip2(cfg.network);

  console.log(`\ngenerating subgraph config for ${network}\n`);

  const deployment = readDeployment(network);
  if (!deployment) {
    throw new Error(`no deployment recorded for ${network}. Run: npm run deploy`);
  }

  let startBlock = deployment.startBlock;
  if (typeof startBlock === "number") {
    ok(`start block ${startBlock.toLocaleString()} (from the deployment record)`);
  } else {
    startBlock = await fetchCreationBlock(cfg.mirrorUrl, deployment.transactionId);
    writeDeployment({ ...deployment, startBlock });
    ok(`start block ${startBlock.toLocaleString()} (looked up, and recorded so this is the last time)`);
  }

  const abi = readArtifact().abi;
  writeFileSync(ABI, JSON.stringify(abi, null, 2) + "\n");
  ok(`wrote subgraph/abis/${CONTRACT_NAME}.json from the compiled artifact`);

  if (!existsSync(TEMPLATE)) throw new Error(`${TEMPLATE} is missing`);
  const substitutions: Record<string, string> = {
    CONTRACT_ADDRESS: deployment.evmAddress,
    START_BLOCK: String(startBlock),
  };
  const manifest = readFileSync(TEMPLATE, "utf8").replace(/\$\{(\w+)\}/g, (_, name: string) => {
    const value = substitutions[name];
    if (value === undefined) throw new Error(`${TEMPLATE} refers to \${${name}}, which is not set here`);
    return value;
  });
  const header = "# Generated by `npm run subgraph:config` - edit subgraph.template.yaml, not this file.\n";
  writeFileSync(MANIFEST, header + manifest);
  ok("wrote subgraph/subgraph.yaml");
  info(`indexing ${deployment.evmAddress} (${deployment.contractId}) from block ${startBlock}`);
}

main().then(
  () => {
    console.log("\ngenerated\n");
  },
  (err: unknown) => {
    console.error(`\nFAILED: ${(err as Error).message}\n`);
    process.exit(1);
  },
);
